sudo: false

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements-travis.txt

before_script:
  - flake8 --ignore=E402

script:
  - ./tests/run_tests.py
  - coverage run ./tests/run_tests.py

after_success: coveralls
